import { WebsiteProject, AuditResult, AuditCheckItem } from '../types';

export function generateSitemapXml(project: WebsiteProject): string {
  const baseUrl = project.url.replace(/\/$/, '');
  const urlEntries = project.sitemapUrls
    .map(
      (item) => `  <url>
    <loc>${baseUrl}${item.path.startsWith('/') ? item.path : '/' + item.path}</loc>
    <lastmod>${item.lastmod}</lastmod>
    <changefreq>${item.changefreq}</changefreq>
    <priority>${item.priority.toFixed(1)}</priority>
  </url>`
    )
    .join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urlEntries}
</urlset>`;
}

export function generateRobotsTxt(project: WebsiteProject): string {
  const sitemapUrl = project.robotsRules.sitemapUrl || `${project.url.replace(/\/$/, '')}/sitemap.xml`;
  const disallows = project.robotsRules.disallowedPaths.length > 0 
    ? project.robotsRules.disallowedPaths.map((p) => `Disallow: ${p}`).join('\n')
    : 'Disallow:';

  return `# Robots.txt generated by Google Site Publisher
# Targets all search engine crawlers with priority for Googlebot

User-agent: *
Allow: /
${disallows}

# Dedicated Googlebot Rules
User-agent: Googlebot
Allow: /
${disallows}

# Image indexing for Google Images
User-agent: Googlebot-Image
Allow: /

# XML Sitemap declaration for Google Search Console
Sitemap: ${sitemapUrl}
`;
}

export function generateSchemaJson(project: WebsiteProject): string {
  const baseUrl = project.url.replace(/\/$/, '');

  let schemaData: Record<string, unknown> = {};

  if (project.schemaType === 'WebApplication') {
    schemaData = {
      '@context': 'https://schema.org',
      '@type': 'WebApplication',
      name: project.name,
      url: baseUrl,
      description: project.description,
      applicationCategory: 'DeveloperApplication',
      operatingSystem: 'All',
      author: {
        '@type': 'Person',
        name: project.author || 'Author',
      },
      offers: {
        '@type': 'Offer',
        price: '0',
        priceCurrency: 'USD',
      },
      aggregateRating: {
        '@type': 'AggregateRating',
        ratingValue: project.rating.toString(),
        reviewCount: project.reviewCount.toString(),
      },
    };
  } else if (project.schemaType === 'Organization') {
    schemaData = {
      '@context': 'https://schema.org',
      '@type': 'Organization',
      name: project.name,
      url: baseUrl,
      logo: project.faviconUrl || `${baseUrl}/logo.png`,
      description: project.description,
      sameAs: [
        `https://twitter.com/${project.twitterHandle.replace('@', '')}`,
      ],
    };
  } else if (project.schemaType === 'FAQPage') {
    schemaData = {
      '@context': 'https://schema.org',
      '@type': 'FAQPage',
      mainEntity: project.faqItems.map((faq) => ({
        '@type': 'Question',
        name: faq.question,
        acceptedAnswer: {
          '@type': 'Answer',
          text: faq.answer,
        },
      })),
    };
  } else if (project.schemaType === 'LocalBusiness') {
    schemaData = {
      '@context': 'https://schema.org',
      '@type': 'LocalBusiness',
      name: project.name,
      image: project.ogImageUrl || `${baseUrl}/business.jpg`,
      description: project.description,
      url: baseUrl,
      telephone: '+8801700000000',
      address: {
        '@type': 'PostalAddress',
        addressLocality: 'Dhaka',
        addressCountry: 'BD',
      },
      priceRange: '$$',
    };
  } else {
    schemaData = {
      '@context': 'https://schema.org',
      '@type': 'Article',
      headline: project.name,
      image: [project.ogImageUrl],
      datePublished: '2026-09-26T08:00:00+06:00',
      dateModified: new Date().toISOString(),
      author: [{
        '@type': 'Person',
        name: project.author,
      }],
      description: project.description,
    };
  }

  return JSON.stringify(schemaData, null, 2);
}

export function generateFullHeadHtml(project: WebsiteProject): string {
  const cleanUrl = project.url.replace(/\/$/, '');
  const schemaJson = generateSchemaJson(project);
  const verificationTag = project.googleVerificationCode 
    ? `  <!-- Google Search Console Verification Meta Tag -->\n  <meta name="google-site-verification" content="${project.googleVerificationCode.replace('google-site-verification=', '')}" />\n` 
    : '';

  return `<!-- ============================================== -->
<!-- GOOGLE-READY HEAD TAGS & SEO META TAGS           -->
<!-- Copy and paste inside your website's <head>     -->
<!-- ============================================== -->

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${project.name}</title>
  <meta name="description" content="${project.description}" />
  <meta name="keywords" content="${project.keywords.join(', ')}" />
  <meta name="author" content="${project.author}" />
  <meta name="robots" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
  <link rel="canonical" href="${cleanUrl}/" />

${verificationTag}
  <!-- OpenGraph (Facebook, LinkedIn, Discord) -->
  <meta property="og:type" content="website" />
  <meta property="og:url" content="${cleanUrl}/" />
  <meta property="og:title" content="${project.name}" />
  <meta property="og:description" content="${project.description}" />
  <meta property="og:image" content="${project.ogImageUrl}" />
  <meta property="og:site_name" content="${project.name}" />
  <meta property="og:locale" content="${project.language === 'bn' ? 'bn_BD' : 'en_US'}" />

  <!-- Twitter / X Cards -->
  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:site" content="${project.twitterHandle}" />
  <meta name="twitter:creator" content="${project.twitterHandle}" />
  <meta name="twitter:title" content="${project.name}" />
  <meta name="twitter:description" content="${project.description}" />
  <meta name="twitter:image" content="${project.ogImageUrl}" />

  <!-- Favicon and Brand Icons -->
  <link rel="icon" type="image/x-icon" href="${project.faviconUrl || '/favicon.ico'}" />

  <!-- Google Structured Data (Schema.org JSON-LD) -->
  <script type="application/ld+json">
${schemaJson}
  </script>
</head>`;
}

export function runSeoAudit(project: WebsiteProject): AuditResult {
  const checks: AuditCheckItem[] = [];

  // 1. HTTPS / SSL
  const hasHttps = project.url.toLowerCase().startsWith('https://');
  checks.push({
    id: 'https',
    title: 'HTTPS & SSL Security',
    titleBn: 'এইচটিটিপিএস (HTTPS) ও এসএসএল সিকিউরিটি',
    category: 'technical',
    status: hasHttps ? 'passed' : 'failed',
    score: hasHttps ? 10 : 0,
    description: hasHttps ? 'Website URL uses secure HTTPS protocol (Required by Google).' : 'Website does not use HTTPS. Google marks insecure sites.',
    descriptionBn: hasHttps ? 'ওয়েবসাইটটি সুরক্ষিত HTTPS প্রোটোকল ব্যবহার করছে (গুগল ইনডেক্সিংয়ে বাধ্যতামূলক)।' : 'ওয়েবসাইটে HTTPS নেই। গুগল অসুরক্ষিত সাইট র্যাংক কমায়।',
    recommendation: 'Ensure your host provides an SSL certificate and redirects HTTP to HTTPS.',
    recommendationBn: 'হোস্টিং প্রোভাইডার থেকে ফ্রি SSL সক্রিয় করুন এবং HTTP থেকে HTTPS এ রিডাইরেক্ট সেট করুন।'
  });

  // 2. Title Tag Length
  const titleLen = project.name.length;
  const titleStatus = titleLen >= 25 && titleLen <= 65 ? 'passed' : titleLen >= 15 ? 'warning' : 'failed';
  checks.push({
    id: 'title_length',
    title: `Title Length (${titleLen} chars)`,
    titleBn: `টাইটেলের দৈর্ঘ্য (${titleLen} অক্ষর)`,
    category: 'meta',
    status: titleStatus,
    score: titleStatus === 'passed' ? 10 : titleStatus === 'warning' ? 6 : 2,
    description: `Optimal Google title tag is between 30 and 60 characters (currently ${titleLen}).`,
    descriptionBn: `গুগল সার্চে আদর্শ টাইটেলের দৈর্ঘ্য ৩০ থেকে ৬০ অক্ষরের মধ্যে হওয়া উচিত (বর্তমানে ${titleLen} অক্ষর)।`,
    recommendation: titleLen < 25 ? 'Add brand or key benefit to make title more descriptive.' : titleLen > 65 ? 'Shorten title so it is not truncated with "..." in Google SERP.' : 'Perfect title length for Google search results.',
    recommendationBn: titleLen < 25 ? 'টাইটেলে সাইটের মূল সুবিধা ও ব্র্যান্ডের নাম যোগ করুন।' : titleLen > 65 ? 'টাইটেল কিছুটা ছোট করুন যাতে গুগল ডট ডট (...) দিয়ে কেটে না দেয়।' : 'গুগল সার্চ রেজাল্টের জন্য একদম পারফেক্ট দৈর্ঘ্য।'
  });

  // 3. Meta Description Length
  const descLen = project.description.length;
  const descStatus = descLen >= 110 && descLen <= 165 ? 'passed' : descLen >= 50 ? 'warning' : 'failed';
  checks.push({
    id: 'desc_length',
    title: `Meta Description (${descLen} chars)`,
    titleBn: `মেটা ডেসক্রিপশন (${descLen} অক্ষর)`,
    category: 'meta',
    status: descStatus,
    score: descStatus === 'passed' ? 10 : descStatus === 'warning' ? 6 : 1,
    description: `Optimal meta description for Google snippets is 120-160 characters (currently ${descLen}).`,
    descriptionBn: `গুগল স্নিপেটের জন্য আদর্শ মেটা ডেসক্রিপশন ১২০-১৬০ অক্ষর (বর্তমানে ${descLen} অক্ষর)।`,
    recommendation: descLen < 110 ? 'Expand description with benefits and clear call-to-action.' : descLen > 165 ? 'Trim slightly to fit Google mobile and desktop search preview snippet.' : 'Ideal meta description length for maximum Google CTR.',
    recommendationBn: descLen < 110 ? 'সাইটের বিবরণ আরও স্পষ্ট করে ১২০ থেকে ১৬০ অক্ষরে বিস্তারিত লিখুন।' : descLen > 165 ? 'কিছুটা সংক্ষেপ করুন যাতে মোবাইলে পুরো লেখা দেখা যায়।' : 'উচ্চ ক্লিক রেট (CTR) পাওয়ার জন্য চমৎকার বিবরণ।'
  });

  // 4. Google Search Console Verification
  const hasGsc = Boolean(project.googleVerificationCode && project.googleVerificationCode.trim().length > 10);
  checks.push({
    id: 'gsc_verification',
    title: 'Google Search Console Verification Tag',
    titleBn: 'গুগল সার্চ কনসোল ভেরিফিকেশন ট্যাগ',
    category: 'indexing',
    status: hasGsc ? 'passed' : 'warning',
    score: hasGsc ? 15 : 5,
    description: hasGsc ? 'Verification meta tag is configured for Google Search Console.' : 'No Google site verification tag detected.',
    descriptionBn: hasGsc ? 'গুগল সার্চ কনসোলের ভেরিফিকেশন মেটা ট্যাগ যুক্ত করা আছে।' : 'গুগল সাইট ভেরিফিকেশন ট্যাগ এখনো দেওয়া হয়নি।',
    recommendation: 'Get your verification code from Google Search Console and paste it into the tag generator.',
    recommendationBn: 'Google Search Console-এ গিয়ে HTML Tag কোডটি কপি করে এখানে পেস্ট করুন।'
  });

  // 5. XML Sitemap
  const hasSitemap = project.sitemapUrls.length > 0;
  checks.push({
    id: 'sitemap',
    title: `XML Sitemap (${project.sitemapUrls.length} URLs)`,
    titleBn: `এক্সএমএল সাইটম্যাপ (${project.sitemapUrls.length} পেজ)`,
    category: 'indexing',
    status: hasSitemap ? 'passed' : 'failed',
    score: hasSitemap ? 10 : 0,
    description: hasSitemap ? `Sitemap contains ${project.sitemapUrls.length} valid internal URLs.` : 'No URLs mapped in XML sitemap.',
    descriptionBn: hasSitemap ? `সাইটম্যাপে ${project.sitemapUrls.length}টি অভ্যন্তরীণ পেজের ইউআরএল রয়েছে।` : 'সাইটম্যাপে কোনো পেজ পাওয়া যায়নি।',
    recommendation: 'Upload sitemap.xml to root and submit URL to Google Search Console.',
    recommendationBn: 'sitemap.xml ফাইলটি সাইটের রুট ফোল্ডারে আপলোড করে সার্চ কনসোলে সাবমিট করুন।'
  });

  // 6. Robots.txt
  const hasRobots = Boolean(project.robotsRules.allowedCrawlers.includes('Googlebot'));
  checks.push({
    id: 'robots',
    title: 'Robots.txt & Googlebot Directives',
    titleBn: 'রোবটস ফাইল (Robots.txt) ও গুগলবট পারমিশন',
    category: 'indexing',
    status: hasRobots ? 'passed' : 'warning',
    score: hasRobots ? 10 : 4,
    description: hasRobots ? 'Robots.txt explicitly welcomes Googlebot and links the sitemap.' : 'Robots.txt does not configure Googlebot specifically.',
    descriptionBn: hasRobots ? 'Robots.txt ফাইল গুগলবটকে ক্রল করার অনুমতি দিচ্ছে এবং সাইটম্যাপ নির্দেশ করছে।' : 'Robots.txt ফাইল গুগলবটের জন্য সুস্পষ্ট নয়।',
    recommendation: 'Ensure your robots.txt contains "User-agent: Googlebot" and "Sitemap: ...".',
    recommendationBn: 'আপনার robots.txt ফাইলে গুগলবটের জন্য Allow এবং Sitemap ডিরেক্টিভ রাখুন।'
  });

  // 7. Schema.org JSON-LD
  const hasSchema = Boolean(project.schemaType);
  checks.push({
    id: 'schema',
    title: `Schema.org JSON-LD (${project.schemaType})`,
    titleBn: `স্কিমা ডেটা (Schema.org JSON-LD)`,
    category: 'meta',
    status: hasSchema ? 'passed' : 'warning',
    score: hasSchema ? 10 : 0,
    description: hasSchema ? `Configured structured data for ${project.schemaType} rich results.` : 'Structured data is missing.',
    descriptionBn: hasSchema ? `${project.schemaType} এর জন্য সমৃদ্ধ স্ট্রাকচার্ড ডেটা তৈরি করা আছে।` : 'স্ট্রাকচার্ড স্কিমা ডেটা নেই।',
    recommendation: 'Google supports rich snippets when JSON-LD is included.',
    recommendationBn: 'গুগল সার্চে স্টার রেটিং ও রিচ স্নাইপেট পাওয়ার জন্য JSON-LD স্কিমা স্ক্রিপ্ট বসান।'
  });

  // 8. OpenGraph & Social Cards
  const hasOg = Boolean(project.ogImageUrl && project.name);
  checks.push({
    id: 'opengraph',
    title: 'OpenGraph & Social Sharing Image',
    titleBn: 'ওপেনগ্রাফ (OpenGraph) ও সোশ্যাল শেয়ারিং ব্যানার',
    category: 'social',
    status: hasOg ? 'passed' : 'warning',
    score: hasOg ? 10 : 3,
    description: hasOg ? 'Full OpenGraph title, description, and preview image defined.' : 'Preview image or OG tags missing.',
    descriptionBn: hasOg ? 'ফেসবুক ও সোশ্যাল মিডিয়ায় শেয়ারের জন্য ইমেজ ও ডেসক্রিপশন সেট করা আছে।' : 'সোশ্যাল মিডিয়া প্রিভিউ ব্যানার ইমেজ পাওয়া যায়নি।',
    recommendation: 'Include a 1200x630px high resolution banner for social shares.',
    recommendationBn: 'ফেসবুক ও টুইটারে সুন্দর দেখতে ১২০০x৬৩০ সাইজের একটি আকর্ষণীয় ইমেজ যোগ করুন।'
  });

  // 9. Mobile Responsive Viewport
  checks.push({
    id: 'viewport',
    title: 'Mobile-Friendly Viewport Tag',
    titleBn: 'মোবাইল ফ্রেন্ডলি ভিউপোর্ট মেটা ট্যাগ',
    category: 'technical',
    status: 'passed',
    score: 10,
    description: 'width=device-width, initial-scale=1.0 is set. Required for Google Mobile-First Indexing.',
    descriptionBn: 'width=device-width, initial-scale=1.0 ট্যাগ প্রস্তুত। গুগল মোবাইল-ফার্স্ট ইনডেক্সিংয়ের জন্য এটি অত্যন্ত জরুরি।',
    recommendation: 'Ensure your UI adapts smoothly across all phone and tablet screen widths.',
    recommendationBn: 'আপনার ডিজাইন যেন সব মোবাইল স্ক্রিনে রেসপনসিভ থাকে তা নিশ্চিত করুন।'
  });

  // 10. Canonical Tag
  checks.push({
    id: 'canonical',
    title: 'Canonical URL Tag',
    titleBn: 'ক্যানোনিকাল (Canonical) ইউআরএল ট্যাগ',
    category: 'indexing',
    status: 'passed',
    score: 5,
    description: `Rel canonical is pointed to ${project.url}/ preventing duplicate content penalties.`,
    descriptionBn: `ক্যানোনিকাল ট্যাগ নির্দেশ করছে আসল ইউআরএলকে, যা ডুপ্লিকেট কন্টেন্ট সমস্যা রোধ করে।`,
    recommendation: 'Keep canonical tag matching your exact primary domain and protocol.',
    recommendationBn: 'ক্যানোনিকাল ট্যাগে সবসময় সাইটের আসল সঠিক ডোমেন অ্যাড্রেস রাখুন।'
  });

  // 11. Favicon & Apple Icon
  const hasFavicon = Boolean(project.faviconUrl);
  checks.push({
    id: 'favicon',
    title: 'Favicon & Search Result Icon',
    titleBn: 'ওয়েবসাইটের ফেভিকন (Favicon)',
    category: 'technical',
    status: hasFavicon ? 'passed' : 'warning',
    score: hasFavicon ? 5 : 2,
    description: hasFavicon ? 'Favicon configured for display beside Google search result URLs.' : 'Default or missing favicon.',
    descriptionBn: hasFavicon ? 'গুগল সার্চ ফলাফলে ইউআরএলের পাশে দেখানোর জন্য ফেভিকন যুক্ত আছে।' : 'ফেভিকন পাওয়া যায়নি।',
    recommendation: 'Provide a crisp 48x48 or SVG favicon so Google search highlights your logo.',
    recommendationBn: 'গুগল সার্চের জন্য ৪৮x৪৮ পিক্সেল বা এসভিজি লোগো আইকন ব্যবহার করুন।'
  });

  // 12. Keywords
  const hasKeywords = project.keywords.length >= 3;
  checks.push({
    id: 'keywords',
    title: `Focus Keywords (${project.keywords.length} defined)`,
    titleBn: `টার্গেট কি-ওয়ার্ড (${project.keywords.length}টি প্রস্তুত)`,
    category: 'meta',
    status: hasKeywords ? 'passed' : 'warning',
    score: hasKeywords ? 5 : 2,
    description: hasKeywords ? 'Keywords defined matching user search intent.' : 'Add more relevant keywords for search intent.',
    descriptionBn: hasKeywords ? 'সার্চ ব্যবহারকারীদের চাহিদামতো সঠিক কি-ওয়ার্ড বাছাই করা আছে।' : 'আরো কয়েকটি প্রাসঙ্গিক সার্চ কি-ওয়ার্ড যোগ করুন।',
    recommendation: 'Focus on 3-5 high intent keywords that your target audience searches for.',
    recommendationBn: 'আপনার অডিয়েন্স গুগলে যেসব শব্দ লিখে খোঁজে এমন ৩-৫টি কি-ওয়ার্ড দিন।'
  });

  const totalScore = checks.reduce((acc, c) => acc + c.score, 0);
  const maxPossible = 100;
  const overallScore = Math.min(100, Math.round((totalScore / maxPossible) * 100));

  const passedCount = checks.filter((c) => c.status === 'passed').length;
  const warningCount = checks.filter((c) => c.status === 'warning').length;
  const failedCount = checks.filter((c) => c.status === 'failed').length;

  return {
    overallScore,
    passedCount,
    warningCount,
    failedCount,
    checks,
  };
}

export function downloadFile(filename: string, content: string, mimeType = 'text/plain') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
